name: Deploy EKS and Sample Pod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region

   
    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --name sudheer-demo --region us-east-1 # Replace with your EKS cluster name and region

    - name: Deploy Sample Pod
      run: kubectl apply -f sample-pod.yaml --validate=false
